name: "SSO OIDC"
guid: "c3ef348c-6871-42c1-8a0e-d03956c9bcf9"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Single Sign-On using OpenID Connect (OIDC)."
description: >
  This plugin enables Single Sign-On (SSO) in Jellyfin using OpenID Connect (OIDC).
  It supports multiple OIDC providers including Google, and authenticates users based
  on the 'email' claim. Providers can be configured via the plugin's settings UI.
category: "Security"
owner: "MatthewThomas"
artifacts:
  - "Jellyfin.Plugin.SsoOidc.dll"
changelog: >
  Initial release with support for Google OpenID Connect and user linking via email claims.
